#!/bin/ksh

set -e

# Fix permissions
/usr/bin/chmod 755 /usr/bin/{rcs,ci,co,ident,merge,rcsclean,rcsdiff,rcsmerge,rlog}
/usr/bin/chown root:root /usr/bin/{rcs,ci,co,ident,merge,rcsclean,rcsdiff,rcsmerge,rlog}
/usr/bin/chmod 644 /usr/share/man/man1/{rcs.1,ci.1,co.1,ident.1,merge.1,rcsclean.1,rcsdiff.1,rcsmerge.1,rlog.1}
/usr/bin/chown root:root /usr/share/man/man1/{rcs.1,ci.1,co.1,ident.1,merge.1,rcsclean.1,rcsdiff.1,rcsmerge.1,rlog.1}
/usr/bin/chmod 644 /usr/share/man/man5/rcsfile.5
/usr/bin/chown root:root /usr/share/man/man5/rcsfile.5
